classdef Groundswell_main_view < handle

% This is Groundswell_main_view, a class to represent the main window of
% the groundswell application.

  properties
    %model;
    controller=[];

    n_chan=[];
    
    tl_view=[];
    
    r=1;
    t_sub=[];
    data_sub_min=[];
    data_sub_max=[];
    
    i_selected=zeros(1,0);

    fig_h=[];
    axes_hs=[];
    
    colors=[];
    x_units='time_s';
    
    % keep handles for all the widgets
    file_menu_h
    open_menu_h
    quit_menu_h
    % the x-axis menu
    x_axis_menu_h
    time_ms_menu_h
    time_s_menu_h
    time_min_menu_h
    time_hr_menu_h
    edit_t_bounds_menu_h
    % the y-axis menu
    y_axis_menu_h
    edit_y_bounds_menu_h
    optimize_selected_y_menu_h
    optimize_all_y_menu_h
    % the mutation menu
    mutation_menu_h
    center_menu_h
    rectify_menu_h
    % the analysis menu
    analysis_menu_h
    power_spectrum_menu_h
    spectrogram_menu_h
    coherency_menu_h
    coherogram_menu_h
    transfer_function_menu_h
    % scroll buttons
    to_start_button_h
    page_left_button_h
    step_left_button_h
    step_right_button_h
    page_right_button_h
    to_end_button_h
    % zoom buttons
    zoom_way_out_button_h
    zoom_out_button_h
    zoom_in_button_h
  end  % properties
  
  methods
    function gsmv=Groundswell_main_view()
      % set the model
      %gsmv.model=gsmm;
      
      % get the screen size so we can position the figure window
      root_units=get(0,'Units');
      set(0,'Units','pixels');
      screen_dims=get(0,'ScreenSize');
      screen_width=screen_dims(3);
      screen_height=screen_dims(4); 
      set(0,'Units',root_units);



      %
      % spec out the layout of the figure
      %

      % layout of the figure on the screen
      screen_left_pad_size=60;
      screen_right_pad_size=60;
      screen_top_pad_size=60;
      screen_bottom_pad_size=60;

      % the figure
      figure_width=screen_width-screen_left_pad_size-screen_right_pad_size;
      figure_height=screen_height-screen_top_pad_size-screen_bottom_pad_size;

      % pick the figure BG color based on the platform
      % except that for now, all platforms are the same
      clr=0.8*ones(1,3);  % gray
      
      %
      % make the figure
      %
      gsmv.fig_h = ...
        figure('Tag','groundswell_figure_h',...
               'Position',[screen_left_pad_size,...
                           screen_bottom_pad_size,...
                           figure_width,figure_height],...
               'Name','groundswell',...
               'NumberTitle','off',...
               'Resize','off',...
               'MenuBar','none',...
               'PaperPositionMode','auto',...
               'Color',clr,...       
               'Renderer','zbuffer');
      %plotedit(groundswell_figure_h,'hidetoolsmenu');



      %
      % add some menus
      %

      % the file menu
      gsmv.file_menu_h=...
        uimenu(gsmv.fig_h,...
               'Tag','file_menu_h',...
               'Label','File');
      gsmv.open_menu_h=...
        uimenu(gsmv.file_menu_h,...
               'Label','Open...',...
               'Tag','open_menu_h');
      % uimenu(file_menu_h,...
      %        'Separator','on',...
      %        'Label','Print Preview...',...
      %        'Tag','print_preview_menu_h',...
      %        'Callback',@(src,event)(gsmv.callback()));
      % uimenu(file_menu_h,...
      %        'Label','Print...',...
      %        'Tag','print_menu_h',...
      %        'Accelerator','p',...
      %        'Callback',@(src,event)(gsmv.callback()));
      gsmv.quit_menu_h=...
        uimenu(gsmv.file_menu_h,...
               'Separator','on',...
               'Label','Quit',...
               'Tag','quit_menu_h');

      % the x-axis menu
      gsmv.x_axis_menu_h=uimenu(gsmv.fig_h,...
                          'Tag','x_axis_menu_h',...
                          'Label','X Axis');
      gsmv.time_ms_menu_h=...
        uimenu(gsmv.x_axis_menu_h,...
               'Tag','time_ms_menu_h',...
               'Label','Time (ms)',...
               'Checked','off',...
               'Enable','off');
      gsmv.time_s_menu_h=...
        uimenu(gsmv.x_axis_menu_h,...
               'Tag','time_s_menu_h',...
               'Label','Time (s)',...
               'Enable','off',...
               'Checked','on');
      gsmv.time_min_menu_h=...
        uimenu(gsmv.x_axis_menu_h,...
               'Tag','time_min_menu_h',...
               'Label','Time (min)',...
               'Checked','off',...
               'Enable','off');
      gsmv.time_hr_menu_h=...
        uimenu(gsmv.x_axis_menu_h,...
               'Tag','time_hr_menu_h',...
               'Label','Time (hr)',...
               'Checked','off',...
               'Enable','off');
      gsmv.edit_t_bounds_menu_h=...
        uimenu(gsmv.x_axis_menu_h,...
               'Separator','on',...
               'Tag','edit_t_bounds_menu_h',...
               'Label','Set range...',...
               'Enable','off');

      % the y-axis menu
      gsmv.y_axis_menu_h=uimenu(gsmv.fig_h,...
                          'Tag','y_axis_menu_h',...
                          'Label','Y Axis');
      gsmv.edit_y_bounds_menu_h=uimenu(gsmv.y_axis_menu_h,...
                                  'Tag','edit_y_bounds_menu_h',...
                                  'Label','Set range...',...
                                  'Enable','off',...
                                  'Callback',@(src,event)(gsmc.edit_y_bounds()));
      gsmv.optimize_selected_y_menu_h=uimenu(gsmv.y_axis_menu_h,...
                                        'Tag','optimize_selected_y_menu_h',...
                                        'Label','Optimize range of selected',...
                                        'Enable','off');
      gsmv.optimize_all_y_menu_h=uimenu(gsmv.y_axis_menu_h,...
                                   'Tag','optimize_all_y_menu_h',...
                                   'Label','Optimize range of all',...
                                   'Enable','off');

      % the mutation menu
      gsmv.mutation_menu_h=uimenu(gsmv.fig_h,...
                             'Tag','mutation_menu_h',...
                             'Label','Mutation');
      gsmv.center_menu_h=uimenu(gsmv.mutation_menu_h,...
                           'Tag','center_menu_h',...
                           'Label','Center',...
                           'Enable','off');
      gsmv.rectify_menu_h=uimenu(gsmv.mutation_menu_h,...
                           'Tag','rectify_menu_h',...
                           'Label','Rectify',...
                           'Enable','off');

      % the analysis menu
      gsmv.analysis_menu_h=uimenu(gsmv.fig_h,...
                             'Tag','analysis_menu_h',...
                             'Label','Analysis');
      gsmv.power_spectrum_menu_h=uimenu(gsmv.analysis_menu_h,...
             'Label','Power spectrum...',...
             'Enable','off',...
             'Tag','power_spectrum_menu_h');
      gsmv.spectrogram_menu_h=uimenu(gsmv.analysis_menu_h,...
             'Label','Spectrogram...',...
             'Enable','off',...
             'Tag','spectrogram_menu_h');
      gsmv.coherency_menu_h=uimenu(gsmv.analysis_menu_h,...
             'Label','Coherency...',...
             'Enable','off',...
             'Tag','coherency_menu_h');
      gsmv.coherogram_menu_h=uimenu(gsmv.analysis_menu_h,...
             'Label','Coherogram...',...
             'Enable','off',...
             'Tag','coherogram_menu_h');
      gsmv.transfer_function_menu_h=uimenu(gsmv.analysis_menu_h,...
             'Label','Transfer function...',...
             'Enable','off',...
             'Tag','transfer_function_menu_h');



      %
      % add some buttons
      %
      % scroll buttons
      gsmv.to_start_button_h = ...
        uicontrol('Parent',gsmv.fig_h,...
                  'Style','pushbutton',...
                  'String','|<',...
                  'Enable','off',...
                  'Tag','to_start_button_h');
      gsmv.page_left_button_h = ...
        uicontrol('Parent',gsmv.fig_h,...
                  'Style','pushbutton',...
                  'String','<<',...
                  'Enable','off',...
                  'Tag','page_left_button_h');
      gsmv.step_left_button_h = ...
        uicontrol('Parent',gsmv.fig_h,...
                  'Style','pushbutton',...
                  'String','<',...
                  'Enable','off',...
                  'Tag','step_left_button_h');
      gsmv.step_right_button_h = ...
        uicontrol('Parent',gsmv.fig_h,...
                  'Style','pushbutton',...
                  'String','>',...
                  'Enable','off',...
                  'Tag','step_right_button_h');
      gsmv.page_right_button_h = ...
        uicontrol('Parent',gsmv.fig_h,...
                  'Style','pushbutton',...
                  'String','>>',...
                  'Enable','off',...
                  'Tag','page_right_button_h');
      gsmv.to_end_button_h = ...
        uicontrol('Parent',gsmv.fig_h,...
                  'Style','pushbutton',...
                  'String','>|',...
                  'Enable','off',...
                  'Tag','to_end_button_h');

      % zoom buttons
      gsmv.zoom_way_out_button_h = ...
        uicontrol('Parent',gsmv.fig_h,...
                  'Style','pushbutton',...
                  'String','--',...
                  'Enable','off',...
                  'Tag','zoom_way_out_button_h');
      gsmv.zoom_out_button_h = ...
        uicontrol('Parent',gsmv.fig_h,...
                  'Style','pushbutton',...
                  'String','-',...
                  'Enable','off',...
                  'Tag','zoom_out_button_h');
      gsmv.zoom_in_button_h = ...
        uicontrol('Parent',gsmv.fig_h,...
                  'Style','pushbutton',...
                  'String','+',...
                  'Enable','off',...
                  'Tag','zoom_in_button_h');

      % set up the instance variables that are non-trivial to init
      gsmv.colors=Groundswell_main_view.make_color_sequence();
      
    end  % constructor
    
  end  % methods

  methods (Static)
    color_sequence = make_color_sequence()
    [x_tick,x_tick_label]=x_tick_from_xl(xl)
  end  % methods (Static)
  
end  % classdef
